import Navbar from "@/components/Navbar";
import "./globals.css";

export const metadata = {
  title: "Photo Feed",
  description: "Generated by Photo Feed",
};

export default function RootLayout({ children }) {
  return (
    <html lang="">
      <body>
        <Navbar />
        <div className="container my-4 lg:my-8">{children}</div>
      </body>
    </html>
  );
}
